/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import java.awt.Image;
import java.net.URL;
import java.util.ArrayList;
import java.util.HashMap;

import java.util.List;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import modelo.Guerrero;
import modelo.Mago;
import modelo.Personaje;

/**
 *
 * @author Usuario
 */
public class Clonados extends javax.swing.JInternalFrame {

    private Personajes personajes;
    private List<Mago> listaMago = new ArrayList<>();
    private List<Guerrero> listaGuerrero = new ArrayList<>();

    /**
     * Creates new form Clonados
     */
    public Clonados(Personajes personajes) {
        initComponents();
        this.personajes = personajes;
        this.mostrarComponentes(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ComboBoxPersonajes = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnMostrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabelImagen = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btnGuardarr = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        ComboBoxPersonajes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Personajes", "Guerreros", "Magos" }));
        ComboBoxPersonajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxPersonajesActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Encanto/Fuerza", "Nombre", "Habilidad", "Equipo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Imagen1", "Imagen2", "Imagen3", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        btnGuardarr.setText("Guardar");
        btnGuardarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarrActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel1.setText("Nuevo Nombre:");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel2.setText("Nueva Habilidad:");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel3.setText("Nuevo Equipo:");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel4.setText("Fuerza/Encanto:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxPersonajes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 221, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                .addComponent(jTextField3))
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                .addComponent(jTextField4))
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(51, 51, 51))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardarr, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 141, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardarr, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(ComboBoxPersonajes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(167, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        jTable1.remove(this);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        int indiceSeleccionado = jTable1.getSelectedRow();
        this.jLabelImagen.setIcon(frameIcon);
        if (indiceSeleccionado != -1) {
            String opcionSeleccionada = ComboBoxPersonajes.getSelectedItem().toString();
            Personaje personajeSeleccionado = personajes.getListaPersonajesClonados().get(indiceSeleccionado);
            String rutaImagen = personajeSeleccionado.getImagen();
            URL imageUrl = getClass().getResource(rutaImagen);
            if (imageUrl != null) {
                ImageIcon originalIcon = new ImageIcon(imageUrl);
                ImageIcon icon = new ImageIcon(originalIcon.getImage().getScaledInstance(jLabelImagen.getWidth(), jLabelImagen.getHeight(), Image.SCALE_DEFAULT));
                jLabelImagen.setIcon(icon);
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo cargar la imagen", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un personaje de la tabla", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void ComboBoxPersonajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxPersonajesActionPerformed
        
        this.mostrarComponentes(false);
        this.ComboBoxPersonajes.getSelectedIndex();
        jLabelImagen.setIcon(frameIcon);
        this.mostarImagen();
        String opcionSeleccionada = ComboBoxPersonajes.getSelectedItem().toString();

        if (opcionSeleccionada.equals("Guerreros")) {
            actualizarTablaGuerreros();
        } else if (opcionSeleccionada.equals("Magos")) {
            actualizarTablaMagos();
        }

        jLabelImagen.setIcon(null);
    }//GEN-LAST:event_ComboBoxPersonajesActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        this.mostrarComponentes(true);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnGuardarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarrActionPerformed
        this.modificarPersonaje();
    }//GEN-LAST:event_btnGuardarrActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxPersonajes;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardarr;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

    private void eliminarPersonaje() {
        int indiceSeleccionado = jTable1.getSelectedRow();

        if (indiceSeleccionado != -1) {
            Personaje personajeClonado = personajes.getListaPersonajesClonados().get(indiceSeleccionado);
            int confirmacion = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas eliminar este personaje clonado?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {
                personajes.getListaPersonajesClonados().remove(personajeClonado);

            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un personaje clonado para eliminar", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void mostrarComponentes(Boolean co) {
        jTextField1.setVisible(co);
        jTextField2.setVisible(co);
        jTextField3.setVisible(co);
        jTextField4.setVisible(co);
        jLabel1.setVisible(co);
        jLabel2.setVisible(co);
        jLabel3.setVisible(co);
        jLabel4.setVisible(co);
        jList1.setVisible(co);
        btnGuardarr.setVisible(co);
    }

    private void modificarPersonaje() {
        int indiceSeleccionado = jTable1.getSelectedRow();

        if (indiceSeleccionado != -1) {
            Personaje personajeClonado = personajes.getListaPersonajesClonados().get(indiceSeleccionado);
            if (personajeClonado instanceof Guerrero) {
                personajeClonado.setNombre(jTextField1.getText());
                personajeClonado.setEquipo(jTextField2.getText());
                personajeClonado.setHabilidad(jTextField3.getText());
                ((Guerrero) personajeClonado).setFuerza(Integer.parseInt(jTextField4.getText()));
                String opcion = jList1.getSelectedValue();
                if (opcion.equalsIgnoreCase("Imagen1")) {
                    ImageIcon guerrero = new ImageIcon(getClass().getResource("/images/img_guerrero_1.jpeg"));
                    ImageIcon icon = new ImageIcon(guerrero.getImage().getScaledInstance(jLabelImagen.getWidth(), jLabelImagen.getHeight(), Image.SCALE_DEFAULT));
                    jLabelImagen.setIcon(icon);
                    String nuevaImagen = "/images/img_guerrero_2.jpeg";
                    personajeClonado.setImagen(nuevaImagen);
                } else if (opcion.equalsIgnoreCase("Imagen2")) {
                    ImageIcon guerrero = new ImageIcon(getClass().getResource("/images/img_guerrero_2.jpeg"));
                    ImageIcon icon = new ImageIcon(guerrero.getImage().getScaledInstance(jLabelImagen.getWidth(), jLabelImagen.getHeight(), Image.SCALE_DEFAULT));
                    jLabelImagen.setIcon(icon);
                    String nuevaImagen = "/images/img_guerrero_2.jpeg";
                    personajeClonado.setImagen(nuevaImagen);
                } else if (opcion.equalsIgnoreCase("Imagen3")) {
                    ImageIcon guerrero = new ImageIcon(getClass().getResource("/imagenes/img_guerrero_3.jpeg"));
                    ImageIcon icon = new ImageIcon(guerrero.getImage().getScaledInstance(jLabelImagen.getWidth(), jLabelImagen.getHeight(), Image.SCALE_DEFAULT));
                    jLabelImagen.setIcon(icon);
                    String nuevaImagen = "/images/img_guerrero_3.jpeg";
                    personajeClonado.setImagen(nuevaImagen);
                }
            } else if (personajeClonado instanceof Mago) {
                System.out.println("mago");
                personajeClonado.setNombre(jTextField1.getText());
                personajeClonado.setEquipo(jTextField2.getText());
                personajeClonado.setHabilidad(jTextField3.getText());
                ((Mago) personajeClonado).setEncanto(jTextField4.getText());
                String opcion = jList1.getSelectedValue();
                if (opcion.equalsIgnoreCase("Imagen1")) {
                    ImageIcon mago = new ImageIcon(getClass().getResource("/images/img_mago_1.jpeg"));
                    ImageIcon icon = new ImageIcon(mago.getImage().getScaledInstance(jLabelImagen.getWidth(), jLabelImagen.getHeight(), Image.SCALE_DEFAULT));
                    jLabelImagen.setIcon(icon);
                    String nuevaImagen = "/images/img_mago_1.jpeg";
                    personajeClonado.setImagen(nuevaImagen);
                } else if (opcion.equalsIgnoreCase("Imagen2")) {
                    ImageIcon mago = new ImageIcon(getClass().getResource("/images/img_mago_3.jpeg"));
                    ImageIcon icon = new ImageIcon(mago.getImage().getScaledInstance(jLabelImagen.getWidth(), jLabelImagen.getHeight(), Image.SCALE_DEFAULT));
                    jLabelImagen.setIcon(icon);
                    String nuevaImagen = "/images/img_mago_3.jpeg";
                    personajeClonado.setImagen(nuevaImagen);
                } else if (opcion.equalsIgnoreCase("Imagen3")) {
                    ImageIcon mago = new ImageIcon(getClass().getResource("/images/img_mago_3.jpg"));
                    ImageIcon icon = new ImageIcon(mago.getImage().getScaledInstance(jLabelImagen.getWidth(), jLabelImagen.getHeight(), Image.SCALE_DEFAULT));
                    jLabelImagen.setIcon(icon);
                    String nuevaImagen = "/images/img_mago_3.jpg";
                    personajeClonado.setImagen(nuevaImagen);
                }
            }

        }
    }

    public void agregarPersonajeClonado(Personaje personajeClonado) {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        // Agregamos una fila al modelo de tabla
        modelo.addRow(new Object[]{personajeClonado.getNombre(), personajeClonado.getHabilidad(), personajeClonado.getEquipo()});
        jTable1.setModel(modelo);
    }

    private void mostarImagen() {
        int indiceSeleccionado = jTable1.getSelectedRow();
        if (indiceSeleccionado != -1) {
            String opcionSeleccionada = ComboBoxPersonajes.getSelectedItem().toString();
            Personaje personajeSeleccionado = personajes.getListaPersonajesClonados().get(indiceSeleccionado);

            if (opcionSeleccionada.equals("Guerreros")) {
                String rutaImagen = personajeSeleccionado.getImagen();
                URL imageUrl = getClass().getResource(rutaImagen);
                if (imageUrl != null) {
                    ImageIcon originalIcon = new ImageIcon(imageUrl);
                    ImageIcon icon = new ImageIcon(originalIcon.getImage().getScaledInstance(jLabelImagen.getWidth(), jLabelImagen.getHeight(), Image.SCALE_DEFAULT));
                    jLabelImagen.setIcon(icon);
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo cargar la imagen", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else if (opcionSeleccionada.equals("Magos")) {
                String rutaImagen = personajeSeleccionado.getImagen();
                URL imageUrl = getClass().getResource(rutaImagen);
                if (imageUrl != null) {
                    ImageIcon originalIcon = new ImageIcon(imageUrl);
                    ImageIcon icon = new ImageIcon(originalIcon.getImage().getScaledInstance(jLabelImagen.getWidth(), jLabelImagen.getHeight(), Image.SCALE_DEFAULT));
                    jLabelImagen.setIcon(icon);
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo cargar la imagen", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }

    private void actualizarTablaGuerreros() {
        DefaultTableModel modelo = (DefaultTableModel) this.jTable1.getModel();
        modelo.setNumRows(0); // Limpiar el modelo antes de agregar nuevas filas

        List<Personaje> listaPersonajesClonados = personajes.getListaPersonajesClonados();

        for (Personaje personajeClonado : listaPersonajesClonados) {
            if (personajeClonado instanceof Guerrero) {
                listaGuerrero.add((Guerrero) personajeClonado);
                int fuerza = ((Guerrero) personajeClonado).getFuerza();
                String nombre = personajeClonado.getNombre();
                String habilidad = personajeClonado.getHabilidad();
                String equipo = personajeClonado.getEquipo();
                Object[] rowData = {fuerza, nombre, habilidad, equipo};
                modelo.addRow(rowData);
            }
        }

        this.jTable1.setModel(modelo);
    }

    private void actualizarTablaMagos() {
        DefaultTableModel modelo = (DefaultTableModel) this.jTable1.getModel();
        modelo.setNumRows(0); // Limpiar el modelo antes de agregar nuevas filas

        List<Personaje> listaPersonajesClonados = personajes.getListaPersonajesClonados();

        for (Personaje personajeClonado : listaPersonajesClonados) {
            if (personajeClonado instanceof Mago) {
                listaMago.add((Mago) personajeClonado);
                String encanto = ((Mago) personajeClonado).getEncanto();
                String nombreM = personajeClonado.getNombre();
                String habilidad = personajeClonado.getHabilidad();
                String equipo = personajeClonado.getEquipo();
                Object[] rowData = {encanto, nombreM, habilidad, equipo};
                modelo.addRow(rowData);
            }
        }

        this.jTable1.setModel(modelo);
    }

}
